modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"

[[mods]]
modId="create_wine_grapes"
version="${file.jarVersion}"
displayName="Create: Wine & Grapes"
description='''
TODO
'''

[[dependencies.create_wine_grapes]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_wine_grapes]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_wine_grapes]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="NONE"
side="BOTH"